DROP TABLE VTPT
select len('2117009001')

UPDATE VTPT SET Thong_So_Kt = '' WHERE Thong_So_Kt IS NULL
UPDATE VTPT SET Ma_Nsx = '' WHERE Ma_Nsx IS NULL
UPDATE VTPT SET Ghi_Chu = '' WHERE Ghi_Chu IS NULL


SELECT * FROM VTPT WHERE Ma_Vt_Moi IN (SELECT MA_VT_MOI FROM VTPT GROUP BY Ma_Vt_Moi HAVING COUNT(*)>1 )

select * from VTPT WHERE Ma_Vt_Moi = '60000211001'

select * from vtpt

SELECT * FROM VTPT WHERE LEN(Ma_Vt_Moi) <> 11  
UPDATE VTPT SET Ma_Cum_Tb = '017', Ma_Vt_Moi = '21017009001' where Ma_Vt_Cu = '11031102'
UPDATE VTPT SET Ma_Cum_Tb = '000', Ma_Vt_Moi = '52000037001' where Ma_Vt_Cu = '43100013'
UPDATE VTPT SET Ma_Dv_Sd = '3',	   Ma_Vt_Moi = '73000151001' where Ma_Vt_Cu = '47550009'
UPDATE VTPT SET Ma_Cum_Tb = '210', Ma_Vt_Moi = '75210219001' where Ma_Vt_Cu = '41100362'
UPDATE VTPT SET Ma_Cum_Tb = '170', Ma_Vt_Moi = '75170567001' where Ma_Vt_Cu = '42501025'


--Phan 1
ALTER TABLE R81DMVT ADD Ma_Vt_Old VARCHAR(20) NOT NULL DEFAULT('')
SELECT * INTO T_VTPT FROM VTPT WHERE Ma_Vt_Moi NOT IN (SELECT MA_VT_MOI FROM VTPT GROUP BY Ma_Vt_Moi HAVING COUNT(*)>1 ) 
UPDATE R81DMVT SET Ma_Vt_Old = Ma_Vt 
ALTER TABLE R02CtNM DISABLE TRIGGER ALL
ALTER TABLE R04CtHD DISABLE TRIGGER ALL
ALTER TABLE R05CtNX DISABLE TRIGGER ALL
ALTER TABLE R80PH DISABLE TRIGGER ALL

DECLARE @_Ma_Vt_Cu VARCHAR(50), @_Ma_Vt_Moi VARCHAR(50), @_SQL VARCHAR(MAX)

DECLARE T_ChangeID CURSOR 
      FOR SELECT Ma_Vt_Cu, Ma_Vt_Moi FROM T_VTPT WHERE Ma_Vt_Cu <> '' AND Ma_Vt_Moi <> '' 
      AND Ma_Nhom = '1'
      
      
OPEN T_ChangeID
FETCH NEXT FROM T_ChangeID INTO @_Ma_Vt_Cu, @_Ma_Vt_Moi

WHILE @@FETCH_STATUS = 0
BEGIN
      
      SET @_SQL = 'EXEC sp_ChangeID ''MA_VT'', ''' + @_Ma_Vt_Cu + ''', ''' + @_Ma_Vt_Moi + '''
                        UPDATE R81DmVt SET Ma_Vt = ''' + @_Ma_Vt_Moi + ''' WHERE Ma_Vt = ''' + @_Ma_Vt_Cu + ''''
      PRINT @_SQL 
      EXECUTE(@_SQL)
      
      FETCH NEXT FROM T_ChangeID INTO @_Ma_Vt_Cu, @_Ma_Vt_Moi
END

CLOSE T_ChangeID
DEALLOCATE T_ChangeID


ALTER TABLE R02CtNM ENABLE TRIGGER ALL
ALTER TABLE R04CtHD ENABLE TRIGGER ALL
ALTER TABLE R05CtNX ENABLE TRIGGER ALL
ALTER TABLE R80PH ENABLE TRIGGER ALL

ALTER TABLE R81DMVT ADD Ma_Nhom VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMVT ADD Ma_Dv_Sd VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMVT ADD Ma_Cum VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMVT ADD Ma_Tb VARCHAR(20) NOT NULL DEFAULT('')
---Phan 2



UPDATE R81DMVT SET Ma_Vt_Old = T2.Ma_Vt_Cu
	FROM R81DMVT T1 JOIN Ma_VtPt T2 ON T1.Ma_Vt = T2.Ma_Vt_Moi

UPDATE R81DMVT SET Thong_So_Kt = T2.Thong_So_Kt, Ma_Tb_Nha_Sx = T2.Ma_Tb_Nha_Sx
	FROM R81DMVT T1 JOIN Ma_VtPt T2 ON T1.Ma_Vt = T2.Ma_Vt_Moi	


select ISNULL(Gia,0) AS Gia from R04CTPO 
WHERE Ma_Vt = '00000107' AND 
(Ma_Vt + CONVERT(VARCHAR(11),Ngay_Ct,103)) IN ( select Ma_Vt + CONVERT(VARCHAR(11),MAX(Ngay_Ct),103) FROM R04CTPO WHERE Ma_Ct like 'DT%' AND Stt <> 'A01040000026042' GROUP BY Ma_Vt)

--select ma_vt from R04CTPO where Stt = 'A01040000026042'
