select * from R00ZONE where Zone_Parent = 'VTTB' 

SELECT * FROM R00COLUMN WHERE Zone IN (select Zone from R00ZONE where Zone_Parent = 'VTTB')


INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'BAOTRICD', N'VTTB', 0, 1, N'Kiểm tra - bảo trì phụ tùng', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'BTSC', N'VTTB', 90, 1, N'Bảo trì sửa chữa', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'DMNHTB', N'VTTB', 0, 1, N'Danh mục nhóm thiết bị', 1)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'DMVTTB', N'VTTB', 0, 1, N'Danh mục thiết bị', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'INHERIT_KHBTSC', N'VTTB', 0, 1, N'Kế hoạch bảo trì sửa chữa', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'KHBT', N'VTTB', 0, 1, N'Kế hoạch bảo trì sửa chữa trong quản lý thiết bị', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'KHBTSC', N'VTTB', 0, 1, N'Kế hoạch bảo trì sửa chữa', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'KHBTSCTT', N'VTTB', 0, 1, N'Kế hoạch bảo trì sửa chữa', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'LSBTSC', N'VTTB', 90, 1, N'Lịch sử bảo trì sửa chữa', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'NOI_SU_DUNG', N'VTTB', 0, 1, N'Nơi sử dụng', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'PTKT', N'VTTB', 0, 1, N'Phụ tùng kèm theo', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'RESOURCEMMTB', N'VTTB', 0, 1, N'Bảng lưu trữ tài nguyên', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'VTDP', N'VTTB', 0, 1, N'Vật tư dự phòng', 0)
INSERT INTO R00ZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand) VALUES(N'YCSC', N'VTTB', 0, 1, N'Yêu cầu sửa chữa', 0)
---
DELETE FROM R00COLUMN WHERE Zone IN (select Zone from R00ZONE where Zone_Parent = 'VTTB')
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMNHTB', N'MA_NH_TB', 150, N'T', 0, 1, N'Mã nhóm thiết bị', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMNHTB', N'TEN_NH_TB', 150, N'T', 0, 1, N'Tên nhóm thiết bị', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'MA_VT', 120, N'T', 0, 1, N'Mã vật tư', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'TEN_VT', 200, N'T', 0, 1, N'Mặt hàng', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'NUOC_SX', 100, N'T', 0, 1, N'Nước sản xuất', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'CONG_SUAT', 60, N'T', 0, 1, N'Công suất', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'NOI_SU_DUNG', 100, N'T', 0, 1, N'Nơi sử dụng', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'NGAY_SU_DUNG', 70, N'D', 0, 1, N'Ngày sử dụng', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'THONG_SO_KY_THUAT', 150, N'T', 0, 1, N'Thông số kỹ thuật', 7, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'TEN_VT_TB_KT', 150, N'T', 0, 1, N'Tên phụ tùng kèm theo', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'MA_VT_TB_KT', 80, N'T', 0, 1, N'Mã phụ tùng kèm theo', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'SO_LUONG', 60, N'N', 2, 1, N'Số lượng', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'MODEL', 80, N'T', 0, 1, N'Model', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'VTDP', N'MA_VT_DP', 100, N'T', 0, 1, N'Mã vật tư', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'VTDP', N'TEN_VT_DP', 100, N'T', 0, 1, N'Mặt hàng', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'VTDP', N'NUOC_SX', 100, N'T', 0, 1, N'Nước sản xuất', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'VTDP', N'THONG_SO_KY_THUAT', 150, N'T', 0, 1, N'Thông số kỹ thuật', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'VTDP', N'TUOI_THO', 150, N'N', 0, 1, N'Tuổi thọ', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'VTDP', N'TEN_DT_CC', 200, N'T', 0, 1, N'Nhà cung cấp', 7, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'NGAY_SUA_CHUA', 120, N'T', 0, 0, N'Ngày', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'NOI_DUNG', 250, N'T', 0, 1, N'Nội dung', 9, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'TINH_TRANG', 250, N'T', 0, 1, N'Tình trạng', 10, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'THOI_GIAN_NGUNG_MAY_DK', 80, N'N', 2, 0, N'Thời gian ngưng máy', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'THOI_GIAN_HOAN_THANH', 120, N'T', 0, 0, N'Thời gian hoàn thành', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'TEN_DT_CBNV_BT', 100, N'T', 0, 0, N'Tên nhân viên bảo trì', 19, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'DUYET', 50, N'K', 0, 1, N'Duyệt', 25, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'RESOURCEMMTB', N'FILE_NAME', 500, N'T', 0, 1, N'Tên file', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'RESOURCEMMTB', N'FILE_TAG', 120, N'T', 0, 1, N'Phần đuôi file', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'TUOI_THO', 60, N'N', 0, 1, N'Tuổi thọ', 8, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'DMVTTB', N'TEN_DT_CC', 100, N'T', 0, 1, N'Nhà cung cấp', 9, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'TEN_VT_TB', 200, N'T', 0, 1, N'Mã vật tư', 8, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'MA_VT_TB', 100, N'T', 0, 0, N'Mã vật tư', 7, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'TRONG_KE_HOACH', 50, N'K', 0, 0, N'Trong kế hoạch', 21, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'MA_VT_TB', 100, N'T', 0, 1, N'Mã vật tư', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'TEN_VT_TB', 200, N'T', 0, 1, N'Mã vật tư', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'HIEN_TRANG', 200, N'T', 0, 1, N'Hiện trạng', 8, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'NGUYEN_NHAN', 200, N'T', 0, 1, N'Nguyên nhân', 9, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'BIEN_PHAP', 200, N'T', 0, 1, N'Biện pháp', 10, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'NGAY_LAP', 70, N'D', 0, 1, N'Ngày lập', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'NOI_SU_DUNG', N'NOI_SU_DUNG', 250, N'T', 0, 1, N'Nơi sử dụng', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'DUYET_YC', 50, N'K', 0, 1, N'Duyệt', 14, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'VI_TRI', 150, N'T', 0, 1, N'Vị trí', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'NGAY_THAY', 70, N'D', 0, 1, N'Ngày thay', 7, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'VTDP', N'TON_CUOI', 100, N'N', 2, 1, N'Tồn cuối', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'TON_CUOI', 60, N'N', 2, 1, N'Tồn cuối', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'NGAY_SUA_CHUA', 70, N'D', 0, 0, N'Ngày', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'NOI_DUNG', 250, N'T', 0, 1, N'Nội dung', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'TINH_TRANG', 250, N'T', 0, 1, N'Tình trạng', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'GIAI_QUYET', 250, N'T', 0, 1, N'Giải quyết', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'THOI_GIAN_NGUNG_MAY', 80, N'N', 2, 0, N'Thời gian ngưng máy', 7, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'THOI_GIAN_HOAN_THANH', 70, N'D', 0, 0, N'Thời gian hoàn thành', 8, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'TEN_DT_CBNV_BT', 100, N'T', 0, 0, N'Tên nhân viên bảo trì', 9, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'DUYET', 50, N'K', 0, 0, N'Duyệt', 12, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'TRONG_KE_HOACH', 50, N'K', 0, 0, N'Trong kế hoạch', 11, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'TYPEOFMAINTENANCE', 100, N'T', 0, 0, N'Loại bảo trì', 24, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'MA_DT_CBNV_YC', 100, N'T', 0, 1, N'Người yêu cầu', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'YCSC', N'TINH_TRANG', 200, N'T', 0, 1, N'Tình trạng', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'DINH_KY_THAY', 80, N'N', 0, 1, N'Định kỳ thay (tháng)', 8, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'NGAY_SUA_CHUA', 120, N'T', 0, 1, N'Ngày', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'THOI_GIAN_HOAN_THANH', 120, N'T', 0, 1, N'Thời gian hoàn thành', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'NOI_DUNG', 300, N'T', 0, 1, N'Nội dung', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'DINH_KY', 80, N'N', 0, 0, N'Định kỳ', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'MA_BP', 80, N'T', 0, 0, N'Mã bộ phận', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'MA_DT_CBNV', 100, N'T', 0, 0, N'Mã nhân viên', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'MA_VT_TB_KT', 80, N'T', 0, 0, N'Mã phụ tùng kèm theo', 8, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'NOI_DUNG', 200, N'T', 0, 0, N'Nội dung', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'THOI_LUONG', 80, N'N', 0, 0, N'Thời lượng', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'TEN_VT_TB_KT', 150, N'T', 0, 1, N'Tên phụ tùng kèm theo', 9, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'NGAY_AP', 70, N'D', 0, 0, N'Ngày áp dụng', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBT', N'NGAY_END', 70, N'D', 0, 0, N'Ngày kết thúc', 7, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'DINH_KY', 80, N'N', 0, 0, N'Định kỳ', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'MA_BP', 80, N'T', 0, 0, N'Mã bộ phận', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'MA_DT_CBNV', 100, N'T', 0, 0, N'Mã nhân viên', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'MA_VT_TB_KT', 80, N'T', 0, 0, N'Mã phụ tùng kèm theo', 9, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'NOI_DUNG', 200, N'T', 0, 0, N'Nội dung', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'TEN_VT_TB_KT', 150, N'T', 0, 1, N'Tên phụ tùng kèm theo', 10, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'THOI_LUONG', 80, N'N', 0, 0, N'Thời lượng', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'MA_VT_TB', 80, N'T', 0, 1, N'Mã vật tư', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'TEN_VT_TB', 200, N'T', 0, 1, N'Mã vật tư', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'NGAY_SUA_CHUA_CC', 70, N'D', 0, 1, N'Ngày kiểm tra cuối cùng', 11, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'NGAY_SUA_CHUA_DK', 70, N'D', 0, 1, N'Ngày kiểm tra tiếp theo', 12, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'LSBTSC', N'TYPEOFMAINTENANCE', 50, N'T', 0, 1, N'Loại bảo trì', 10, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSC', N'DUYET_KT', 50, N'K', 0, 1, N'Duyệt kiểm tra', 13, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'NGOAI_KE_HOACH', 50, N'K', 0, 0, N'Ngoài kế hoạch', 22, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BTSC', N'THOI_GIAN_NGUNG_MAY', 80, N'N', 2, 1, N'Thời gian ngưng máy', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'TEN_BP_YC', 120, N'T', 0, 1, N'Bộ phận yêu cầu', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'TEN_BP', 120, N'T', 0, 1, N'Bộ phận thực hiện', 9, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'TEN_DT_CBNV_BT', 120, N'T', 0, 1, N'Người thực hiện', 10, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'GHI_CHU', 200, N'T', 0, 1, N'Ghi chú', 12, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'DINH_KY', 80, N'N', 0, 0, N'Định kỳ', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'DUYET_KT', 50, N'K', 0, 1, N'Duyệt kiểm tra', 15, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'MA_BP', 80, N'T', 0, 0, N'Mã bộ phận', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'MA_DT_CBNV', 100, N'T', 0, 0, N'Mã nhân viên', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'MA_VT_TB', 80, N'T', 0, 1, N'Mã vật tư', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'MA_VT_TB_KT', 80, N'T', 0, 0, N'Mã phụ tùng kèm theo', 9, N'3', 0, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'NGAY_SUA_CHUA_CC', 70, N'D', 0, 1, N'Ngày kiểm tra cuối cùng', 13, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'NGAY_SUA_CHUA_DK', 70, N'D', 0, 1, N'Ngày kiểm tra tiếp theo', 14, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'NOI_DUNG', 200, N'T', 0, 0, N'Nội dung', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'TEN_VT_TB', 200, N'T', 0, 1, N'Mã vật tư', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'TEN_VT_TB_KT', 150, N'T', 0, 1, N'Tên phụ tùng kèm theo', 10, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'THOI_LUONG', 80, N'N', 0, 0, N'Thời lượng', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'KIEM_TRA', 80, N'K', 0, 1, N'Kiểm tra', 11, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'KHBTSCTT', N'SUA_CHUA', 80, N'K', 0, 1, N'Sửa chữa', 12, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'DINH_KY', 80, N'N', 0, 0, N'Định kỳ', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'DUYET_KT', 50, N'K', 0, 1, N'Duyệt kiểm tra', 15, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'KIEM_TRA', 60, N'K', 0, 1, N'Kiểm tra', 11, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'MA_BP', 80, N'T', 0, 0, N'Mã bộ phận', 5, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'MA_DT_CBNV', 100, N'T', 0, 0, N'Mã nhân viên', 6, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'MA_VT_TB', 80, N'T', 0, 1, N'Mã vật tư', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'MA_VT_TB_KT', 80, N'T', 0, 0, N'Mã phụ tùng kèm theo', 9, N'3', 0, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'NGAY_SUA_CHUA_CC', 70, N'D', 0, 1, N'Ngày kiểm tra cuối cùng', 13, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'NGAY_SUA_CHUA_DK', 70, N'D', 0, 1, N'Ngày kiểm tra tiếp theo', 14, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'NOI_DUNG', 200, N'T', 0, 0, N'Nội dung', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'SUA_CHUA', 60, N'K', 0, 1, N'Sửa chữa', 12, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'TEN_VT_TB', 200, N'T', 0, 1, N'Mã vật tư', 2, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'TEN_VT_TB_KT', 150, N'T', 0, 1, N'Tên phụ tùng kèm theo', 10, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'THOI_LUONG', 80, N'N', 0, 0, N'Thời lượng', 4, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'INHERIT_KHBTSC', N'CHON', 60, N'K', 0, 1, N'Chọn', 0, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'TEN_VT_TB', 200, N'T', 0, 1, N'Mã vật tư', 1, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'NGAY_LAP', 120, N'T', 0, 1, N'Ngày lập', 3, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'KET_QUA', 200, N'T', 0, 1, N'Kết quả', 11, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'SL_TON_MIN', 80, N'N', 2, 1, N'Sl tồn tối thiểu', 9, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'PTKT', N'SL_TON_MAX', 80, N'N', 2, 1, N'Sl tồn tối đa', 10, N'3', 1, 0)
INSERT INTO R00COLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Stt, Show_Type, Visible, Is_Customize) VALUES(N'BAOTRICD', N'HOAN_THANH', 60, N'K', 0, 0, N'Hoàn thành', 13, N'3', 1, 0)
