


CREATE TABLE R05KIEMKE
(
	Ident00 int IDENTITY  PRIMARY KEY  NOT NULL ,
	Ngay_Ct DATE NOT NULL  DEFAULT (''),--Ngay kiem ke
	Ma_Vt varchar (20) NOT NULL  DEFAULT (''),
	Ma_Kho varchar (20) NOT NULL  DEFAULT (''),
	So_Luong money NOT NULL  DEFAULT ((0)),	
	Ma_DvCs varchar (3) NOT NULL  DEFAULT ('')
)

CREATE UNIQUE INDEX Kiem_Ke ON R05KIEMKE(Ngay_Ct, Ma_Kho, Ma_Vt, Ma_DvCs)
CREATE INDEX Ngay_Ct ON R05KIEMKE(Ngay_Ct)
CREATE INDEX Ma_Kho ON R05KIEMKE(Ma_Kho)
CREATE INDEX Ma_Vt ON R05KIEMKE(Ma_Vt)
CREATE INDEX Ma_DvCs ON R05KIEMKE(Ma_DvCs)

ALTER TABLE R05KIEMKE ADD FOREIGN KEY (Ma_DvCs) REFERENCES R00DMDVCS(Ma_DvCs)

select * FROM R05KIEMKE

ALTER TABLE R05KIEMKE ADD Create_Log VARCHAR(50) NOT NULL DEFAULT('')
ALTER TABLE R05KIEMKE ADD LastModify_Log VARCHAR(50) NOT NULL DEFAULT('')

SELECT * FROM R00COLUMN WHERE Zone = 'CDV_VIEW'
SELECT * FROM R00COLUMN WHERE Zone = 'KIEMKE_VIEW'

EXEC sp_GetColumnList 'R00PERMISSION'

INSERT INTO R00PERMISSION ( Member_ID, Object_ID, Allow_Access, Allow_New, Allow_Edit, Allow_Delete, Allow_View)
SELECT  'NGOCNN', Object_ID, Allow_Access, Allow_New, Allow_Edit, Allow_Delete, Allow_View
 FROM R00PERMISSION WHERE OBJECT_ID NOT IN (SELECT OBJECT_ID FROM R00PERMISSION WHERE Member_ID = 'NGOCNN') AND Member_ID = 'QUANGNN' 


SELECT * FROM R05CTN_BARCODE WHERE Barcode = '01160144067'
SELECT * FROM R05CTN_BARCODE WHERE Barcode = '01160144068'

SELECT * FROM R81DMBARCODE WHERE Barcode = '01160144067'
SELECT * FROM R81DMBARCODE WHERE Barcode = '01160144068'
