ALTER TABLE R81DMBARCODE ADD Ngay_Nhap DATE NOT NULL DEFAULT('19000101')
UPDATE R81DMBARCODE SET Ngay_Nhap = Ngay_Sx
UPDATE R81DMBARCODE SET Ngay_Nhap = T2.Ngay_Sx
	FROM R81DMBARCODE T1 JOIN R81DMCA T2 ON T1.Ma_Ca = T2.Ma_Ca

--ADD R00OBJECT: ACCESS_NEW_BARCODE
--sp_PrintBarcode
--sp_Update_DmBarcode
--fn_GetNewBarcode

ALTER TABLE R81DMBARCODE DROP COLUMN Ngay_Sx

CREATE TABLE R81DMCTAUTO
(
	Ma_Ct VARCHAR(5) PRIMARY KEY,
	Description NVARCHAR(200) NOT NULL DEFAULT(''),
	So_Xe VARCHAR(20) NOT NULL DEFAULT(''),
	So_Xa_Lan_Tau VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Dt VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Vt_Sp VARCHAR(20) NOT NULL DEFAULT(''),
	Dien_Giai NVARCHAR(200) NOT NULL DEFAULT(''),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
)

ALTER TABLE R81DMBARCODE DROP DF__R81DMBARC__Is_Kh__6815D5B2
ALTER TABLE R81DMBARCODE DROP COLUMN Is_Kho_Le

ALTER TABLE R81DMBARCODE DROP DF__R81DMBARC__Is_Kh__6721B179
ALTER TABLE R81DMBARCODE DROP COLUMN Is_Kho_Chan

ALTER TABLE R80PH_SCALE ADD Stt_Org VARCHAR(15) NOT NULL DEFAULT('')
ALTER TABLE R80PH_SCALE ADD Ma_Vt_Org VARCHAR(1000) NOT NULL DEFAULT('')
ALTER TABLE R05CTX_BARCODE ADD Ma_Vt_Org VARCHAR(20) NOT NULL DEFAULT('')
