DROP TABLE R81DMTINCHAP
GO
CREATE TABLE R81DMTINCHAP
(
	Ident00 INT IDENTITY PRIMARY KEY,
	Ma_Dt VARCHAR(20),
	Ngay_Ap DATETIME,
	Tien_Tin_Chap MONEY,
	Create_Log VARCHAR(35),
	LastModify_Log VARCHAR(35)
)

ALTER TABLE R81DMVT ADD Ma_Nhom VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMVT ADD Ma_Dv_Sd VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMVT ADD Ma_Cum VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMVT ADD Ma_Tb VARCHAR(20) NOT NULL DEFAULT('')

select  TOP 10 * from R81DMVT

ALTER TABLE R81DMVT DROP DF__R81DMVT__So_Luon__42996CE9
ALTER TABLE R81DMVT DROP COLUMN So_Luong_Ld

ALTER TABLE R81DMVT DROP DF__R81DMVT__CHON__79756BDE
ALTER TABLE R81DMVT DROP COLUMN Chon

CREATE TABLE R81DMCUMTB
(
	Ident00 INT IDENTITY PRIMARY KEY,
	Ma_Cum VARCHAR(20),
	Ten_Cum NVARCHAR(200),
	Ghi_Chu NVARCHAR(100)
)

drop table CUM_TB

delete from CUM_TB where mA_CUM = ''
UPDATE CUM_TB SET Ghi_Chu = '' where Ghi_Chu IS NULL

ALTER TABLE R81DMCUMTB ALTER COLUMN Ten_Cum NVARCHAR(200)
ALTER TABLE R81DMCUMTB ADD Create_Log VARCHAR(50) NOT NULL DEFAULT('')
ALTER TABLE R81DMCUMTB ADD LastModify_Log VARCHAR(50) NOT NULL DEFAULT('')
INSERT INTO R81DMCUMTB(Ma_Cum, Ten_Cum, Ghi_Chu)
SELECT Ma_Cum, Ten_Cum, MAX(Ghi_Chu) FROM CUM_TB GROUP BY Ma_Cum, Ten_Cum

---25/7
ALTER TABLE R04CTPO ADD Phan_Hoi_KHVT VARCHAR(200) NOT NULL DEFAULT('')