--R81EQuipment
--DROP TABLE R81EQUIPMENT
CREATE TABLE R81EQUIPMENT
(
	Host_IP VARCHAR(20) PRIMARY KEY,
	Host_Name NVARCHAR(100) NOT NULL DEFAULT(''),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT('')
)
CREATE INDEX ID_Host_IP ON R81EQUIPMENT(Host_IP)
SELECT * FROM R81EQUIPMENT

--R81EQUIPMENTINFO
--DROP TABLE R81EQUIPMENTINFO
CREATE TABLE R81EQUIPMENTINFO
(
	Ident00 INT IDENTITY(1,1) PRIMARY KEY,
	Host_IP VARCHAR(20) NOT NULL DEFAULT(''),
	Equip_ID VARCHAR(50) NOT NULL DEFAULT(''),
	Description NVARCHAR(100) NOT NULL DEFAULT(''),
	Port_Name VARCHAR(20) NOT NULL DEFAULT(''),
	BaudRate VARCHAR(20) NOT NULL DEFAULT(0),
	Parity VARCHAR(20) NOT NULL DEFAULT(''),
	DataBits VARCHAR(10) NOT NULL DEFAULT(0),
	StopBits VARCHAR(20) NOT NULL DEFAULT(''),
	Handshake VARCHAR(20) NOT NULL DEFAULT(''),
	Zero_Coefficient MONEY NOT NULL DEFAULT(0),
	Span_Coefficient MONEY NOT NULL DEFAULT(0),
	Net_Weight_Min MONEY NOT NULL DEFAULT(0),
	Net_Weight_Max MONEY NOT NULL DEFAULT(0),
	Slopes_Up MONEY NOT NULL DEFAULT(0),
	Slopes_Down MONEY NOT NULL DEFAULT(0),
	Stable_Num INT NOT NULL DEFAULT(0),
	Num_Ticket_Print INT NOT NULL DEFAULT(0),
	Print_Barcode VARCHAR(100) NOT NULL DEFAULT(''),
	Print_Report VARCHAR(100) NOT NULL DEFAULT(''),
	Print_Eticket VARCHAR(100) NOT NULL DEFAULT(''),
	Status_Input_Type VARCHAR(20) NOT NULL DEFAULT(''),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT('')
)
CREATE INDEX ID_Host_IP ON R81EQUIPMENTINFO(Host_IP)
CREATE INDEX ID_Equip_ID ON R81EQUIPMENTINFO(Equip_ID)
SELECT * FROM R81EQUIPMENTINFO

ALTER TABLE R81EQUIPMENTINFO ADD STX VARCHAR(10) NOT NULL DEFAULT('')
ALTER TABLE R81EQUIPMENTINFO ADD ETX VARCHAR(10) NOT NULL DEFAULT('')
ALTER TABLE R81EQUIPMENTINFO ADD Value_Len VARCHAR(10) NOT NULL DEFAULT('')
ALTER TABLE R81EQUIPMENTINFO ADD PLC_Port_Name VARCHAR(20) NOT NULL DEFAULT('')

--Table R81DMLOT
CREATE TABLE R81DMLOTS
(
	Lot_ID VARCHAR(20) PRIMARY KEY,
	Lot_Name NVARCHAR(100) NOT NULL DEFAULT(''),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('*')
)
CREATE INDEX UI_Lot_ID ON R81DMLOTS(Lot_ID)
SELECT * FROM R81DMLOTS

--Table R81DMCA
--DROP TABLE R81DMCA
CREATE TABLE R81DMCA
(
	Ma_Ca VARCHAR(20) PRIMARY KEY,
	Ca CHAR(1) NOT NULL DEFAULT(''),
	Ngay_Sx DATE NOT NULL DEFAULT('19000101'),
	Gio_Begin TIME(7) NOT NULL DEFAULT(''),
	Gio_End TIME(7) NOT NULL DEFAULT(''),
	Ma_Dt_CbNv_TC VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Dt_CbNv_KCS VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Dt_CbNv_Can VARCHAR(20) NOT NULL DEFAULT(''),
	Ended BIT NOT NULL DEFAULT(0),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('*')
)
CREATE INDEX UI_Ma_Ca ON R81DMCA(Ma_Ca)
SELECT * FROM R81DMCA

--Danh mục chất lượng
--DROP TABLE R81DMCL
CREATE TABLE R81DMCL
(
	Ma_CL VARCHAR(20) PRIMARY KEY,
	Ten_CL NVARCHAR(100) NOT NULL DEFAULT(''),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('*')
)
CREATE INDEX UI_Ma_CL ON R81DMCL(Ma_CL)
SELECT * FROM R81DMCL

--ALTER TABLE
SELECT * FROM R81DMVT where Ma_vt = 'ABC'

ALTER TABLE R81DMVT ADD Length MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMVT ADD Diameter MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMVT ADD DMax MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMVT ADD DMin MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMVT ADD BarWeight DECIMAL(18,6) NOT NULL DEFAULT(0)
ALTER TABLE R81DMVT ADD MinWeight MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMVT ADD MaxWeight MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMVT ADD Num_Bars INT NOT NULL DEFAULT(0)

--Table R81DMBARCODE
--DROP TABLE R81DMBARCODE
CREATE TABLE R81DMBARCODE
(
	Barcode VARCHAR(20) PRIMARY KEY,
	Loai_Barcode VARCHAR(5) NOT NULL DEFAULT(''), --TT-Thep thanh, TC-Thep cuon
	Ngay_Sx DATE NOT NULL DEFAULT('19000101'),
	Ma_Vt_Sp VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Ca VARCHAR(20) NOT NULL DEFAULT(''),
	Standard_ID VARCHAR(20) NOT NULL DEFAULT(''),
	Grade_ID VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_CL VARCHAR(20) NOT NULL DEFAULT(''),
	Lot_ID VARCHAR(20) NOT NULL DEFAULT(''),
	Num_Lot VARCHAR(50) NOT NULL DEFAULT(''),
	No_Melt VARCHAR(20) NOT NULL DEFAULT(''),
	Num_Bars MONEY NOT NULL DEFAULT(0),
	Length MONEY NOT NULL DEFAULT(0),
	Code MONEY NOT NULL DEFAULT(0),
	So_Luong MONEY NOT NULL DEFAULT(0),
	So_Luong_Barem MONEY NOT NULL DEFAULT(0),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('*')
)
CREATE INDEX UI_Barcode ON R81DMBARCODE(Barcode)
CREATE INDEX UI_Ma_Vt_Sp ON R81DMBARCODE(Ma_Vt_Sp)
CREATE INDEX UI_Ma_Ca ON R81DMBARCODE(Ma_Ca)
CREATE INDEX UI_Standard_ID ON R81DMBARCODE(Standard_ID)
CREATE INDEX UI_Grade_ID ON R81DMBARCODE(Grade_ID)
CREATE INDEX UI_Ma_CL ON R81DMBARCODE(Ma_CL)
CREATE INDEX UI_Lot_ID ON R81DMBARCODE(Lot_ID)

SELECT * FROM R81DMBARCODE

--Table R05CTNX_BARCODE
--DROP TABLE R05CTN_BARCODE
CREATE TABLE R05CTN_BARCODE
(
	Ident00 INT IDENTITY(1, 1) PRIMARY KEY,
	Ma_Ct VARCHAR(5) NOT NULL DEFAULT(''),
	Ngay_Ct DATE NOT NULL DEFAULT(''),
	Ma_Kho VARCHAR(20) NOT NULL DEFAULT(''),
	Barcode VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Vt VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Ca VARCHAR(20) NOT NULL DEFAULT(''),
	So_Luong MONEY NOT NULL DEFAULT(0),
	So_Luong_Barem MONEY NOT NULL DEFAULT(0),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_DvCs VARCHAR(3) NOT NULL DEFAULT('*')
)
CREATE INDEX UI_Barcode ON R05CTN_BARCODE(Barcode)
ALTER TABLE R05CTN_BARCODE ADD FOREIGN KEY (Ma_Ct) REFERENCES R00DMCT(Ma_Ct)
ALTER TABLE R05CTN_BARCODE ADD FOREIGN KEY (Ma_DvCs) REFERENCES R00DMDVCS(Ma_DvCs)

SELECT * FROM R05CTN_BARCODE

--Table R80PH_SCALE
--DROP TABLE R80PH_SCALE
CREATE TABLE R80PH_SCALE
(
	Stt VARCHAR(15) PRIMARY KEY,
	Ma_Ct VARCHAR(5) NOT NULL DEFAULT(''),
	So_Ct VARCHAR(20) NOT NULL DEFAULT(''),
	Ngay_Ct DATE NOT NULL DEFAULT('19000101'),
	Ma_Dt VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Dt_CbNv_Vao VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Dt_CbNv_Ra VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Vt VARCHAR(20) NOT NULL DEFAULT(''),
	Dien_Giai NVARCHAR(200) NOT NULL DEFAULT(''),
	So_Xe VARCHAR(20) NOT NULL DEFAULT(''),
	So_Luong_Vao MONEY NOT NULL DEFAULT(0),
	So_Luong_Ra MONEY NOT NULL DEFAULT(0),
	So_Luong MONEY NOT NULL DEFAULT(0),
	Time_In DATETIME NOT NULL DEFAULT(''),
	Time_Out DATETIME NOT NULL DEFAULT(''),
	Duyet BIT NOT NULL DEFAULT(0),
	Ly_Do NVARCHAR(200) NOT NULL DEFAULT(''),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_DvCs VARCHAR(3) NOT NULL DEFAULT('')
)
CREATE INDEX Stt ON R80PH_SCALE(Stt)
CREATE INDEX Ngay_Ct ON R80PH_SCALE(Ngay_Ct)
CREATE INDEX So_Ct ON R80PH_SCALE(So_Ct)
CREATE INDEX Ma_Dt ON R80PH_SCALE(Ma_Dt)
CREATE INDEX Ma_Vt ON R80PH_SCALE(Ma_Vt)
CREATE INDEX Dien_Giai ON R80PH_SCALE(Dien_Giai)
CREATE INDEX Ma_DvCs ON R80PH_SCALE(Ma_DvCs)
CREATE INDEX Ma_Ct ON R80PH_SCALE(Ma_Ct)

ALTER TABLE R80PH_SCALE ADD FOREIGN KEY (Ma_DvCs) REFERENCES R00DMDVCS(Ma_DvCs)
ALTER TABLE R80PH_SCALE ADD FOREIGN KEY (Ma_Ct) REFERENCES R00DMCT(Ma_Ct)


--Table R05CTX_BARCODE
--DROP TABLE R05CTX_BARCODE
CREATE TABLE R05CTX_BARCODE
(
	Ident00 INT IDENTITY(1,1) PRIMARY KEY,
	Stt VARCHAR(15) NOT NULL DEFAULT(''),
	Stt0 INT NOT NULL DEFAULT(0),
	Ma_NVu VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Ct VARCHAR(5) NOT NULL DEFAULT(''),
	Ngay_Ct DATE NOT NULL DEFAULT('19000101'),
	Barcode VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Dt VARCHAR(20) NOT NULL DEFAULT(''),
	Dien_Giai NVARCHAR(200) NOT NULL DEFAULT(''),
	Ma_Kho VARCHAR(20) NOT NULL DEFAULT(''),
	Ma_Vt VARCHAR(20) NOT NULL DEFAULT(''),
	Dvt NVARCHAR(50) NOT NULL DEFAULT(''),
	So_Luong MONEY NOT NULL DEFAULT(0),
	So_Luong_Barem MONEY NOT NULL DEFAULT(0),
	Stt_Org VARCHAR(15) NOT NULL DEFAULT(''),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_DvCs VARCHAR(3) NOT NULL DEFAULT('')
)
CREATE UNIQUE INDEX Stt_Stt0 ON R05CTX_BARCODE (Stt,Stt0)
ALTER TABLE R05CTX_BARCODE ADD FOREIGN KEY (Stt) REFERENCES R80PH_SCALE(Stt)
ALTER TABLE R05CTX_BARCODE ADD FOREIGN KEY (Ma_Ct) REFERENCES R00DMCT(Ma_Ct)
ALTER TABLE R05CTX_BARCODE ADD FOREIGN KEY (Ma_DvCs) REFERENCES R00DMDVCS(Ma_DvCs)


---------------------
ALTER TABLE R81DMCA ADD Ma_Vt_Sp_Last VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMCA ADD Grade_ID_Last VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMCA ADD Ma_CL_Last VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMCA ADD No_Melt_Last VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMCA ADD Lot_ID_Last VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMCA ADD Num_Lot_Last VARCHAR(20) NOT NULL DEFAULT('')
ALTER TABLE R81DMCA ADD Length_Last VARCHAR(20) NOT NULL DEFAULT(0)

SELECT * FROM R81DMCA

EXEC sp_rename 'R81EQUIPMENTINFO.Num_Stabilize', 'Stable_Count', 'column'

ALTER TABLE R81EQUIPMENTINFO ADD Stable_Time INT NOT NULL DEFAULT(0)
ALTER TABLE R81EQUIPMENTINFO ADD Stable_Range INT NOT NULL DEFAULT(0)

SELECT * FROM R81EQUIPMENTINFO

--TABLE R81DMCOTINH
--DROP TABLE R81DMCOTINH
CREATE TABLE R81DMCOTINH
(
	Ma_Co_Tinh VARCHAR(20) PRIMARY KEY,
	Description NVARCHAR(200) NOT NULL DEFAULT(''),
	Grade_ID VARCHAR(20) NOT NULL DEFAULT(''),
	DMin MONEY NOT NULL DEFAULT(0),
	DMax MONEY NOT NULL DEFAULT(0),
	YeildP_Min MONEY NOT NULL DEFAULT(0),
	YeildP_Max MONEY NOT NULL DEFAULT(0),
	YeildH_Min MONEY NOT NULL DEFAULT(0),
	YeildH_Max MONEY NOT NULL DEFAULT(0),
	Yeild24H_Min MONEY NOT NULL DEFAULT(0),
	Yeild24H_Max MONEY NOT NULL DEFAULT(0),
	TensionP_Min MONEY NOT NULL DEFAULT(0),
	TensionP_Max MONEY NOT NULL DEFAULT(0),
	TensionH_Min MONEY NOT NULL DEFAULT(0),
	TensionH_Max MONEY NOT NULL DEFAULT(0),
	Tension24H_Min MONEY NOT NULL DEFAULT(0),
	Tension24H_Max MONEY NOT NULL DEFAULT(0),
	Elong_Min MONEY NOT NULL DEFAULT(0),
	Elong_Max MONEY NOT NULL DEFAULT(0),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('*')
)
CREATE INDEX Grade_ID ON R81DMCOTINH(Grade_ID)
CREATE INDEX Ma_Data ON R81DMCOTINH(Ma_Data)

SELECT * FROM R81DMCOTINH

--Danh mục thành phần hóa học
--DROP TABLE R81DMTPHH
CREATE TABLE R81DMTPHH
(
	Ma_TPHH VARCHAR(20) PRIMARY KEY,
	Description NVARCHAR(200) NOT NULL DEFAULT(''),
	Grade_ID VARCHAR(20) NOT NULL DEFAULT(''),
	Fe_Min MONEY NOT NULL DEFAULT(0),--Sắt
	Fe_Max MONEY NOT NULL DEFAULT(0),
	C_Min MONEY NOT NULL DEFAULT(0),--Cacbon
	C_Max MONEY NOT NULL DEFAULT(0),
	Mn_Min MONEY NOT NULL DEFAULT(0),--Mangan
	Mn_Max MONEY NOT NULL DEFAULT(0),
	Si_Min MONEY NOT NULL DEFAULT(0),--Silic
	Si_Max MONEY NOT NULL DEFAULT(0),
	P_Min MONEY NOT NULL DEFAULT(0),--Photpho
	P_Max MONEY NOT NULL DEFAULT(0),
	S_Min MONEY NOT NULL DEFAULT(0),--Lưu huỳnh
	S_Max MONEY NOT NULL DEFAULT(0),
	Cr_Min MONEY NOT NULL DEFAULT(0),--Crom
	Cr_Max MONEY NOT NULL DEFAULT(0),
	Ni_Min MONEY NOT NULL DEFAULT(0),--Niken
	Ni_Max MONEY NOT NULL DEFAULT(0),
	Mo_Min MONEY NOT NULL DEFAULT(0),--Molypden
	Mo_Max MONEY NOT NULL DEFAULT(0),
	Cu_Min MONEY NOT NULL DEFAULT(0),--Đồng
	Cu_Max MONEY NOT NULL DEFAULT(0),
	Al_Min MONEY NOT NULL DEFAULT(0),--Nhôm
	Al_Max MONEY NOT NULL DEFAULT(0),
	V_Min MONEY NOT NULL DEFAULT(0),--Vanadi
	V_Max MONEY NOT NULL DEFAULT(0),
	W_Min MONEY NOT NULL DEFAULT(0),--Wolfram
	W_Max MONEY NOT NULL DEFAULT(0),
	Sn_Min MONEY NOT NULL DEFAULT(0),--Thiếc
	Sn_Max MONEY NOT NULL DEFAULT(0),
	Ass_Min MONEY NOT NULL DEFAULT(0),--Asen
	Ass_Max MONEY NOT NULL DEFAULT(0),
	Cueq_Min MONEY NOT NULL DEFAULT(0),
	Cueq_Max MONEY NOT NULL DEFAULT(0),
	Ceq_Min MONEY NOT NULL DEFAULT(0),
	Ceq_Max MONEY NOT NULL DEFAULT(0),
	C_Mn_6_Min MONEY NOT NULL DEFAULT(0),
	C_Mn_6_Max MONEY NOT NULL DEFAULT(0),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('*')
)
CREATE INDEX Grade_ID ON R81DMTPHH(Grade_ID)
CREATE INDEX Ma_Data ON R81DMTPHH(Ma_Data)


--
ALTER TABLE R05CTX_BARCODE ADD Num_Bars MONEY NOT NULL DEFAULT(0)
ALTER TABLE R05CTX_BARCODE ADD So_Ct VARCHAR(20) NOT NULL DEFAULT('')

ALTER TABLE R81DMBARCODE ADD Try_ID VARCHAR(50) NOT NULL DEFAULT('')
ALTER TABLE R81DMBARCODE ADD Yeild MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Tension MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD ELong MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Bend_Test BIT NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Is_Output BIT NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Printed INT NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Remark NVARCHAR(200) NOT NULL DEFAULT('')
ALTER TABLE R81DMBARCODE ADD Remark_KCS NVARCHAR(200) NOT NULL DEFAULT('')
ALTER TABLE R81DMBARCODE ADD LastModify_Log_KCS VARCHAR(35) NOT NULL DEFAULT('')

SELECT * FROM R05CTN_BARCODE
SELECT * FROM R81DMBARCODE

SELECT * FROM R80PH_SCALE
SELECT * FROM R05CTX_BARCODE

ALTER TABLE R81DMBARCODE ADD Num_Bars_Embryos MONEY NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Ly_Do NVARCHAR(200) NOT NULL DEFAULT('')
ALTER TABLE R81DMCA ADD Num_Bars_Embryos_Last MONEY NOT NULL DEFAULT(0)

ALTER TABLE R80PH_SCALE ADD SL_Xe_Hang MONEY NOT NULL DEFAULT(0)
ALTER TABLE R80PH_SCALE ADD TSL_Barcode MONEY NOT NULL DEFAULT(0)
ALTER TABLE R80PH_SCALE ADD TSo_Barcode MONEY NOT NULL DEFAULT(0)
ALTER TABLE R80PH_SCALE ADD SL_QDinh MONEY NOT NULL DEFAULT(0)
ALTER TABLE R80PH_SCALE ADD SL_CL MONEY NOT NULL DEFAULT(0)
ALTER TABLE R80PH_SCALE ADD Ghi_Chu_QDinh NVARCHAR(200) NOT NULL DEFAULT('')

--Table Formular
CREATE TABLE R81FORMULAR_SCALE
(
	Formular_ID VARCHAR(50) PRIMARY KEY,
	Description NVARCHAR(200) NOT NULL DEFAULT(''),
	Condition VARCHAR(100) NOT NULL DEFAULT(''),
	Formular VARCHAR(200) NOT NULL DEFAULT(''),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('')
)

--Table R80SDV_BARCODE
CREATE TABLE R80SDV_BARCODE
(
	Ident00 INT IDENTITY(1,1) PRIMARY KEY,
	Stt VARCHAR(15) NOT NULL DEFAULT(''),
	Nam INT NOT NULL DEFAULT(0),
	Ngay_Ct DATE NOT NULL DEFAULT('19000101'),
	Ma_Kho VARCHAR(20) NOT NULL DEFAULT(''),
	Barcode VARCHAR(50) NOT NULL DEFAULT(''),
	Ton_Dau MONEY NOT NULL DEFAULT(0),
	Ton_Dau_Barem MONEY NOT NULL DEFAULT(0),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_DvCs VARCHAR(3) NOT NULL DEFAULT('')
)
CREATE UNIQUE INDEX Stt ON R80SDV_BARCODE(Stt)
CREATE INDEX Ngay_Ct ON R80SDV_BARCODE(Ngay_Ct)
CREATE INDEX Ma_Kho ON R80SDV_BARCODE(Ma_Kho)
CREATE INDEX Barcode ON R80SDV_BARCODE(Barcode)
CREATE INDEX Ma_DvCs ON R80SDV_BARCODE(Ma_DvCs)


--Thanh phan hoa hoc
CREATE TABLE R81MTTPHH
(
	Ident00 INT IDENTITY(1,1) PRIMARY KEY,
	Description NVARCHAR(200) NOT NULL DEFAULT(''),
	No_Melt VARCHAR(20) NOT NULL DEFAULT(''),
	Num_Bars_Embryos MONEY NOT NULL DEFAULT(0),
	Grade_Name NVARCHAR(200) NOT NULL DEFAULT(''),
	Pattern_Pos VARCHAR(50) NOT NULL DEFAULT(''),--Vi tri mau
	Billet_Size VARCHAR(50) NOT NULL DEFAULT(''),--Kích thước size
	Ngay_Sx DATE NOT NULL DEFAULT('19000101'),
	Ca VARCHAR(5) NOT NULL DEFAULT(''),
	Fe MONEY NOT NULL DEFAULT(0),--Sắt
	C MONEY NOT NULL DEFAULT(0),--Cacbon
	Mn MONEY NOT NULL DEFAULT(0),--Mangan
	Si MONEY NOT NULL DEFAULT(0),--Silic
	P MONEY NOT NULL DEFAULT(0),--Photpho
	S MONEY NOT NULL DEFAULT(0),--Lưu huỳnh
	Cr MONEY NOT NULL DEFAULT(0),--Crom
	Ni MONEY NOT NULL DEFAULT(0),--Niken
	Mo MONEY NOT NULL DEFAULT(0),--Molypden
	Cu MONEY NOT NULL DEFAULT(0),--Đồng
	Al MONEY NOT NULL DEFAULT(0),--Nhôm
	V MONEY NOT NULL DEFAULT(0),--Vanadi
	W MONEY NOT NULL DEFAULT(0),--Wolfram
	Sn MONEY NOT NULL DEFAULT(0),--Thiếc
	Ass MONEY NOT NULL DEFAULT(0),--Asen
	Cueq MONEY NOT NULL DEFAULT(0),
	Ceq MONEY NOT NULL DEFAULT(0),
	C_Mn_6 MONEY NOT NULL DEFAULT(0),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('*')
)
CREATE INDEX No_Melt ON R81MTTPHH(No_Melt)
CREATE INDEX Ma_Data ON R81MTTPHH(Ma_Data)

SELECT * FROM R81MTTPHH

ALTER TABLE R81DMBARCODE ADD Is_Wait_Process BIT NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Is_Kho_Chan BIT NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Is_Kho_Le BIT NOT NULL DEFAULT(0)
ALTER TABLE R81DMBARCODE ADD Is_Thu_Pham BIT NOT NULL DEFAULT(0)

ALTER TABLE R81DMBARCODE ADD Date_Process DATE NOT NULL DEFAULT('19000101')
ALTER TABLE R81DMBARCODE ADD Input_Type VARCHAR(50) NOT NULL DEFAULT('')
ALTER TABLE R81DMBARCODE ADD State_Process BIT NOT NULL DEFAULT(0)

ALTER TABLE R81DMCA ADD Ma_Vt_Sp_Last VARCHAR(20) NOT NULL DEFAULT('')

SELECT TOP 10 * FROM R81DMBARCODE
ALTER TABLE R81DMBARCODE ADD Barcode_Org VARCHAR(1000) NOT NULL DEFAULT('')

ALTER TABLE R80PH_SCALE ADD Can VARCHAR(5) NOT NULL DEFAULT('')

ALTER TABLE R81DMBARCODE ADD LastModify_Log_Status VARCHAR(35) NOT NULL DEFAULT('')

--DROP TABLE R00LOCKED_BARCODE
CREATE TABLE R00LOCKED_BARCODE(	Ident00 INT IDENTITY(1,1) PRIMARY KEY,	Ma_DvCs VARCHAR(3) NOT NULL DEFAULT(''),	Ngay_Locked1 DATETIME NOT NULL DEFAULT('19000101'),	Ngay_Locked2 DATETIME NOT NULL DEFAULT('19000101'),	Locked_Type VARCHAR(10) NOT NULL  DEFAULT ('*')	)
CREATE UNIQUE INDEX UI_Locked_Barcode ON R00LOCKED_BARCODE (Ma_DvCs,Ngay_Locked1,Ngay_Locked2,Locked_Type)

INSERT R00LOCKED_BARCODE(Ma_DvCs, Ngay_Locked1, Ngay_Locked2, Locked_Type)
SELECT Ma_DvCs, Ngay_Locked1, Ngay_Locked2, Locked_Type
	FROM R00LOCKED

SELECT * FROM R00LOCKED_BARCODE


--DROP TABLE R05CTN_BARCODE
--sp_CloneTable 'R05CTX_BARCODE', 'R05CTN_BARCODE'
CREATE TABLE R05CTN_BARCODE(	Ident00 int IDENTITY  NOT NULL ,	Stt varchar (15) NOT NULL  DEFAULT (''),	Stt0 int NOT NULL  DEFAULT ((0)),	Ma_NVu varchar (20) NOT NULL  DEFAULT (''),	Ma_Ct varchar (5) NOT NULL  DEFAULT (''),	Ngay_Ct date NOT NULL  DEFAULT ('19000101'),	Barcode varchar (20) NOT NULL  DEFAULT (''),	Ma_Dt varchar (20) NOT NULL  DEFAULT (''),	Dien_Giai nvarchar (200) NOT NULL  DEFAULT (''),	Ma_Kho varchar (20) NOT NULL  DEFAULT (''),	Ma_Vt varchar (20) NOT NULL  DEFAULT (''),	Dvt nvarchar (50) NOT NULL  DEFAULT (''),	So_Luong money NOT NULL  DEFAULT ((0)),		So_Luong_Barem money NOT NULL  DEFAULT ((0)),	Num_Bars money NOT NULL  DEFAULT ((0)),	Stt_Org varchar (15) NOT NULL  DEFAULT (''),	Create_Log varchar (35) NOT NULL  DEFAULT (''),	LastModify_Log varchar (35) NOT NULL  DEFAULT (''),	Ma_DvCs varchar (3) NOT NULL  DEFAULT (''),	So_Ct varchar (20) NOT NULL  DEFAULT (''),	Ma_Vt_Sp varchar (20) NOT NULL  DEFAULT (''),	Ma_Vt_Org varchar (20) NOT NULL  DEFAULT (''))
CREATE UNIQUE INDEX Stt_Stt0 ON R05CTN_BARCODE (Stt,Stt0)
ALTER TABLE R05CTN_BARCODE ADD FOREIGN KEY (Stt) REFERENCES R80PH_SCALE(Stt)
ALTER TABLE R05CTN_BARCODE ADD FOREIGN KEY (Ma_Ct) REFERENCES R00DMCT(Ma_Ct)
ALTER TABLE R05CTN_BARCODE ADD FOREIGN KEY (Ma_DvCs) REFERENCES R00DMDVCS(Ma_DvCs)

--DROP TABLE R81DMSIZE
CREATE TABLE R81DMSIZE
(
	Ma_Size VARCHAR(20) PRIMARY KEY,
	Ten_Size NVARCHAR(100) NOT NULL DEFAULT(''),
	Length MONEY NOT NULL DEFAULT(0),
	Diameter MONEY NOT NULL DEFAULT(0),
	DMin MONEY NOT NULL DEFAULT(0),
	DMax MONEY NOT NULL DEFAULT(0),
	BarWeight DECIMAL(18, 6) NOT NULL DEFAULT(0),
	MinWeight MONEY NOT NULL DEFAULT(0),
	MaxWeight MONEY NOT NULL DEFAULT(0),
	Num_Bars INT NOT NULL DEFAULT(0),
	Ngay_Begin DATE NOT NULL DEFAULT('19000101'),
	Ngay_End DATE NOT NULL DEFAULT('19000101'),
	Create_Log VARCHAR(35) NOT NULL DEFAULT(''),
	LastModify_Log VARCHAR(35) NOT NULL DEFAULT(''),
	Ma_Data VARCHAR(3) NOT NULL DEFAULT('*')
)
SELECT * FROM R81DMSIZE
INSERT R81DMSIZE(Ma_Size, Ten_Size, Length, Diameter, DMin, DMax, BarWeight, MinWeight, MaxWeight, Num_Bars)
SELECT Ma_Vt, Ten_Vt, Length, Diameter, DMin, DMax, BarWeight, MinWeight, MaxWeight, Num_Bars
	FROM R81DMVT WHERE Ma_Nh_Vt = 'THEPCAY'


ALTER TABLE R80PH_SCALE ADD Printed_In INT NOT NULL DEFAULT(0)
ALTER TABLE R80PH_SCALE ADD Printed_Out INT NOT NULL DEFAULT(0)