CREATE TABLE R06CTTSHH
(
	Ident00 INT IDENTITY PRIMARY KEY,
	Stt VARCHAR(15) NOT NULL DEFAULT(''),
	Ma_Vt_Ts VARCHAR(20) NOT NULL DEFAULT (''),
	Trang_Thai_Ts VARCHAR(20) NOT NULL DEFAULT (''),
	Ngay_Ct DATETIME NOT NULL DEFAULT ('')
)


SELECT * FROM R06CTTS