SELECT * FROM 
(SELECT Ma_Vt, Stt, Stt_Org, Stt0_Org, So_luong FROM R04CTPO WHERE Ma_Ct LIKE 'BB%' AND Stt_Org <> '') T1 
	LEFT JOIN 
(SELECT Stt, Stt_Org, Ma_Vt, Stt0_Org, So_Luong from R02CTNM WHERE Stt_Org <> '') T2 
ON T1.Stt_Org = T2.Stt_Org AND T1.Ma_Vt = T2.Ma_Vt AND T1.Stt0_Org = T2.Stt0_Org


CREATE TABLE R02TTPH
(
	Stt VARCHAR(15) PRIMARY KEY,
	Ngay_Ct DATETIME,
	Ma_Bp VARCHAR(20),
	Ma_Dt_CbNv VARCHAR(20),
	Dien_Giai NVARCHAR(200),
	TTien3 MONEY,
	TTien0 MONEY
)
GO
CREATE TABLE R02TTCT
(
	Ident00 INT PRIMARY KEY,
	Stt VARCHAR(15) ,
	Loai_Ct VARCHAR(2),
	Ngay_Ct0 DATETIME,
	So_Ct0 VARCHAR(20),
	Tien3 MONEY,
	Tien MONEY
)

ALTER TABLE [dbo].[R02TTCT]  WITH CHECK ADD  CONSTRAINT [FK__R02TTCT__Stt__62EF9734] FOREIGN KEY([Stt])
REFERENCES [dbo].[R02TTPH] ([Stt])
GO

-- VTTHTX

--DROP TABLE DMTHTX
--GO
update DMTHTX set PXC = 0 WHERE PXC IS NULL
update DMTHTX set PXCD = 0 WHERE PXCD IS NULL
update DMTHTX set QLCL = 0 WHERE QLCL IS NULL
update DMTHTX set VPP = 0 WHERE VPP IS NULL

INSERT INTO R81DMVTTHTX (MA_VT, MA_BP, GHI_CHU, DINH_MUC)
SELECT Ma_Vt, 'PXLUYEN', ISNULL(Ghi_Chu,''), PXL FROM DMTHTX WHERE MA_VT IS NOT NULL AND MA_VT IN (SELECT MA_VT FROM R81DMVT) AND PXL <> 0
UNION ALL
SELECT Ma_Vt, 'PXCAN', ISNULL(Ghi_Chu,''), PXC FROM DMTHTX WHERE MA_VT IS NOT NULL AND MA_VT IN (SELECT MA_VT FROM R81DMVT) AND PXC <> 0
UNION ALL
SELECT Ma_Vt, 'PXCD', ISNULL(Ghi_Chu,''), PXCD FROM DMTHTX WHERE MA_VT IS NOT NULL AND MA_VT IN (SELECT MA_VT FROM R81DMVT) AND PXCD <> 0
UNION ALL
SELECT Ma_Vt, 'PQLCL', ISNULL(Ghi_Chu,''), QLCL FROM DMTHTX WHERE MA_VT IS NOT NULL AND MA_VT IN (SELECT MA_VT FROM R81DMVT) AND QLCL <> 0
UNION ALL
SELECT Ma_Vt, '', ISNULL(Ghi_Chu,''), VPP FROM DMTHTX WHERE MA_VT IS NOT NULL AND MA_VT IN (SELECT MA_VT FROM R81DMVT) AND VPP <> 0

SELECT Ma_Bp FROM R81DMBP
SELECT * FROM DMTHTX
CREATE TABLE R81DMVTTHTX
(
	Ident00 INT IDENTITY PRIMARY KEY,
	Ma_Vt VARCHAR(20),
	Ma_Bp VARCHAR(20),
	Ghi_Chu NVARCHAR(200),
	Dinh_Muc MONEY,
	Create_Log VARCHAR(50),
	LastModify_Log VARCHAR(50),
	Ngay_Begin DATETIME,
	Ngay_End DATETIME
)

-- EXEC sp_Xuat_PYC_THTX '20160515'
ALTER PROCEDURE sp_Xuat_PYC_THTX
(
	@Ngay_Ct DATETIME,
	@Ma_Data VARCHAR(5) = 'A01'
)
AS
BEGIN
	DECLARE @_Key VARCHAR(1000) = '0 = 0 AND Ma_Kho LIKE ''01%'''
	
	SELECT Ma_Vt, Ma_Kho, Ton_Dau AS Ton_Cuoi
		INTO #T_TonCuoi0
		FROM R80SDV
		WHERE 0 = 1
	
	EXEC sp_TonCuoiList @Ngay_Ct, @_Key, '#T_TonCuoi0',@Ma_Data
	
	SELECT Ma_Vt, SUM(Ton_Cuoi) AS Ton_Cuoi INTO #T_TonCuoi FROM #T_TonCuoi0 GROUP BY Ma_Vt
	
	SELECT T1.Ma_Vt, t2.Ten_Vt, T2.Dvt, T1.Ghi_Chu AS Muc_Dich, CASE WHEN Dinh_Muc - ISNULL(Ton_Cuoi,0) > 0 THEN Dinh_Muc - ISNULL(Ton_Cuoi,0) ELSE 0 END AS So_Luong, Dinh_Muc, ISNULL(Ton_Cuoi,0) AS Ton_Cuoi
		INTO #T_DinhMuc
		FROM (SELECT Ma_Vt, MAX(Ghi_Chu) AS Ghi_Chu, SUM(Dinh_Muc) AS Dinh_Muc FROM R81DMVTTHTX GROUP BY Ma_Vt) T1 JOIN R81DMVT T2 ON T1.Ma_Vt = T2.Ma_Vt
			LEFT JOIN #T_TonCuoi T3 ON T1.Ma_Vt = T3.Ma_Vt
	
	SELECT * FROM #T_DinhMuc WHERE So_Luong > 0
END